### ISSUE TITLE
Fehlende Liegenschaft: Ludwigstr. 14

### ISSUE THREAD

**Issue by silanea** [lmu-navigator/common#9]
In der Hoffnung, dass der Report hier an der richtigen Stelle ist: Es fehlt die Liegenschaft Ludwigstr. 14 mit Sitz des [Lehrstuhls für Bayerische Geschichte und Vergleichende Landesgeschichte mit besonderer Berücksichtigung der Neuzeit](http://www.bg.geschichte.uni-muenchen.de/ueber_uns/index.html) sowie des [Instituts für Bayerische Geschichte](http://www.bayerischegeschichte.uni-muenchen.de/index.html) samt zugehöriger Bibliothek. Es handelt sich hier um Räumlichkeiten im Hauptstaatsarchiv; sollte in der LMU kein entsprechender Raumplan vorliegen, können wir gerne einen auftreiben (Kontakt über mich hier auf GH oder auf dem Dienstweg an das [Sekretariat Prof. Kramer](http://www.bg.geschichte.uni-muenchen.de/personen/sekr-und-bib/woellert_claudia/index.html)).

**Comment by MaxMediaPictures** [comment]
Leider gibt es ein paar Gebäude für die wir keine Raumpläne erhalten. Wir bekommen die Daten vom Referat IV.I (Planung, Bau, Bewirtschaftung) und importieren diese vollständig. Das sollten die selben Pläne sein, die auch auf der offiziellen Website mit den [Gebäudeübersichten ](http://www.uni-muenchen.de/ueber_die_lmu/standorte/lageplaene/index.html) zu finden sind. 

Ich würde in diesem Fall empfehlen Kontakt mit dem Referat IV.I aufzunehmen (cafm@lmu.de). Wir können die Pläne dann im nächsten Update-Zyklus mit aufnehmen.
